# Generated by Django 3.2.9 on 2021-11-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_app', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
