# Generated by Django 3.2.9 on 2021-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_app', '0003_loan_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_loaned',
            field=models.BooleanField(default=False),
        ),
    ]
