# Generated by Django 3.2.9 on 2021-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_app', '0006_alter_loan_loaner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.TextField(),
        ),
    ]
