# Generated by Django 3.2.9 on 2021-12-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg_app', '0007_alter_loan_loaner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
